spring:
  data:
    redis:
      port: 6379
      host: localhost

bungie:
  api:
    callbackUrl: ${application.callback.url}/bungie/callback

discord:
  api:
    callbackUrl: ${application.callback.url}/discord/callback

server:
  port: 8080
  ssl:
    enabled: false

application:
  callback:
    # Replace with your own callback url masking port 8080 to run locally
    url: https://ab91-2600-1700-4390-a930-10cf-aff6-c3c2-4a8c.ngrok-free.app